- content/contribute/_index.md
> Update build steps in contributing page

- content/license.md
> Update copyright year to 2019-2020

- content/installation/ElasticSearch/_index.md
- content/installation/Mattermost/_index.md
- content/installation/Slack/_index.md
- content/installation/Webhook/_index.md
> Fix helm installation commands

- static/js/learn.js
> Override theme learn.js

- content/installation/ElasticSearch/_index.md
- content/installation/Mattermost/_index.md
- content/installation/Slack/_index.md
- content/installation/Webhook/_index.md
Fixes: https://github.com/infracloudio/botkube/issues/275
> Fix helm2 installation command options

- content/_index.md
> Fix homepage section overlap issue on smaller screens

- netlify.toml
> Fix join.botkube.io link

- content/installation/Teams/_index.md
- Add prerequisites section about having details to expose an endpoint
- Fix grammatical errors
> Add prerequisites and grammar fixes on Teams page

- netlify.toml
> Update Slack workspace invite link

- .gitignore
- content/contribute/_index.md
- content/contribute/release.md
- hack/release.sh
- Prepare release instruction
- Document both `botkube` and `botkube-docs` release process
- Make the release script cross-platform
See also https://github.com/infracloudio/botkube/pull/580
Resolves https://github.com/infracloudio/botkube/issues/586
You can follow the instruction to test the changes on your fork 🙂  Make sure that you use changes from both https://github.com/infracloudio/botkube/pull/580 and this PR (https://github.com/infracloudio/botkube-docs/pull/74)
> Document release process for BotKube

- content/contribute/elasticsearch-develop.md
- content/contribute/ms-teams-develop.md
- content/contribute/release.md
- content/contribute/webhook-develop.md
Based on: https://github.com/infracloudio/botkube/pull/603#issuecomment-1147337280
> Introduce instruction for Elasticsearch and Outgoing Webhook development

- .gitignore
- config.toml
- content/privacy.md
- layouts/partials/header.html
This PR brings the following changes:
- Add Cookie policy and website disclaimer
- Ignore JetBrains IDE configuration files in repo
- Add styles for Cookie banner
See https://github.com/kubeshop/botkube/issues/506
I used Termly.com to generate the legal documents. The Privacy Policy for BotKube app will be changed later once analytics are implemented
Once this PR is merged, I will enable the following cookie banner as a Cloudflare App (https://www.cloudflare.com/apps/cookie-consent):
https://cookie-policy.botkube-docs-dcb.pages.dev/privacy/
Unfortunately, I cannot install cookie banner here, as I would need to add a custom domain to Cloudflare.
> Add Cookie policy and website disclaimer

- content/contribute/_index.md
- Update local development guide
This PR synchronizes docs changes from https://github.com/kubeshop/botkube/pull/640.
> Update local development guide

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- Add CODEOWNERS
- Add SECURITY.md
- Add CONTRIBUTING.md
- Modify the bug and feature issue templates
- Modify pull request template
- Reworked the main README.md
Fixes https://github.com/kubeshop/botkube/issues/594
> Add CODEOWENRS, SECURITY.md, CONTRIBUTING.md, tmpls and update README.md

- content/privacy.md
- Describe events collection details in Privacy Policy
As a part of PR https://github.com/kubeshop/botkube/pull/644 we collect more data about handled events, the privacy policy needs to be updated to be fully transparent with users.
https://github.com/kubeshop/botkube/issues/506
> Describe events collection details in Privacy Policy

- .github/CODEOWNERS
- Added @ezodude as a code owner.
N/A
> Add @ezodude as a code owner

- content/configuration/_index.md
- content/configuration/executor.md
- content/configuration/source.md
- content/examples/_index.md
- content/installation/Discord/_index.md
- content/installation/ElasticSearch/_index.md
- content/installation/Mattermost/_index.md
- content/installation/Slack/_index.md
- content/installation/Teams/_index.md
- content/installation/Webhook/_index.md
- Update the `namespace` property syntax according to the https://github.com/kubeshop/botkube/pull/686
Fix https://github.com/kubeshop/botkube/issues/679
> Update `namespace` property syntax

- .github/CODEOWNERS
- Added @huseyinbabal as a code owner.
N/A
> Add new code owner (@huseyinbabal)

- content/configuration/source.md
- Update recommendation merging strategy description
https://github.com/kubeshop/botkube/issues/684
See also https://github.com/kubeshop/botkube/pull/689
> Update recommendation merging strategy description

- content/contribute/release.md
- Apply minor changes to the release doc
> Apply minor changes to the release doc

- content/installation/Discord/_index.md
- content/installation/Teams/_index.md
- Update Discord install doc
- Update MS Teams install doc
PreviewURL: https://fix-install-docs.botkube-docs.pages.dev/
In docs I specified the 0.13 version but I ran the same command with the 0.13.0-rc.1.
```bash
export CLUSTER_NAME=dev
export ALLOW_KUBECTL=true
helm install --version v0.13.0-rc.1 botkube --namespace botkube --create-namespace \
--set communications.default-group.discord.enabled=true \
--set communications.default-group.discord.channels.default.id=${DISCORD_CHANNEL_ID} \
--set communications.default-group.discord.botID=${DISCORD_BOT_ID} \
--set communications.default-group.discord.token=${DISCORD_TOKEN} \
--set settings.clusterName=${CLUSTER_NAME} \
--set executors.kubectl-read-only.kubectl.enabled=${ALLOW_KUBECTL} \
--set …
```
> Update Discord & MS Teams install doc

- content/installation/ElasticSearch/_index.md
- Instructions follow the new values.yaml.
- Removed optional index type.
- Instructions follow the new values.yaml.
- Removed optional index type.
See also [Release 0.13 and promote it](https://github.com/kubeshop/botkube/issues/595)
> Update Elasticsearch installation docs

- .github/CODEOWNERS
- `botkube-docs-reviewers` team is added as codeowner
> Codeowners update for doc team
